# Generated by Django 5.1.5 on 2025-02-24 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                ("sam_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "system_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pf_no", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                (
                    "password_last_set",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "password_never_expires",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "password_expired",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("last_login", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "creation_date",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "account_expiration_date",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "system_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "organization_unit",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "when_changed",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("subsidiary", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "application",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "system_violations",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "unidentified",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dormancy", models.CharField(blank=True, max_length=100, null=True)),
                ("aging", models.CharField(blank=True, max_length=50, null=True)),
                ("duplicates", models.CharField(blank=True, max_length=10, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("exception", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "ad",
                "verbose_name_plural": "ad",
                "db_table": "ad",
            },
        ),
        migrations.CreateModel(
            name="applications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "application_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "application_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("on_premise", "On Premise"),
                            ("third_party", "Third Party"),
                            ("user_portal", "User Portal"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("app_description", models.TextField(blank=True, null=True)),
                (
                    "app_support_admin_email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("tier", models.CharField(blank=True, max_length=200, null=True)),
                ("department", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_review", models.DateTimeField(blank=True, null=True)),
                ("number_of_users", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "applications",
                "verbose_name_plural": "applications",
                "db_table": "applications",
            },
        ),
        migrations.CreateModel(
            name="column_mapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_field", models.CharField(max_length=255)),
                ("excel_header", models.CharField(max_length=255)),
                ("application", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "column_mapping",
                "verbose_name_plural": "column_mapping",
                "db_table": "column_mapping",
            },
        ),
        migrations.CreateModel(
            name="staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pf_no", models.CharField(blank=True, max_length=50, null=True)),
                ("sam_name", models.CharField(blank=True, max_length=100, null=True)),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                ("supervisor", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "supervisor_pf",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "employee_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "employee_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("subsidiary", models.CharField(blank=True, max_length=200, null=True)),
                ("department", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("branch", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "actual_end_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "application",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "supervisor_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "staff",
                "verbose_name_plural": "staff",
                "db_table": "staff",
            },
        ),
        migrations.CreateModel(
            name="system_users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pf_no", models.CharField(blank=True, max_length=50, null=True)),
                ("sam_name", models.CharField(blank=True, max_length=100, null=True)),
                ("user_id", models.CharField(blank=True, max_length=50, null=True)),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                (
                    "creation_date",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "system_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("last_login", models.CharField(blank=True, max_length=200, null=True)),
                ("branch", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "system_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("work_class", models.CharField(blank=True, max_length=100, null=True)),
                ("role_id", models.CharField(blank=True, max_length=100, null=True)),
                ("subsidiary", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "application",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "system_violations",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "unidentified",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dormancy", models.CharField(blank=True, max_length=100, null=True)),
                ("aging", models.CharField(blank=True, max_length=50, null=True)),
                ("duplicates", models.CharField(blank=True, max_length=10, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "organization_unit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("comment", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "system_users",
                "verbose_name_plural": "system_users",
                "db_table": "system_users",
            },
        ),
        migrations.CreateModel(
            name="login_credentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=200, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                ("reset_date", models.DateTimeField(blank=True, null=True)),
                ("host", models.CharField(blank=True, max_length=200, null=True)),
                ("port", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="access_review.applications",
                    ),
                ),
            ],
            options={
                "verbose_name": "login_credentials",
                "verbose_name_plural": "login_credentials",
                "db_table": "login_credentials",
            },
        ),
    ]
