# Generated by Django 5.1.5 on 2025-02-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="login_credentials",
            name="host",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="login_credentials",
            name="port",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="login_credentials",
            name="service_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
