# Generated by Django 5.1.5 on 2025-02-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_review", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="definition_of_headers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.TimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("example", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "definition_of_headers",
                "verbose_name_plural": "definition_of_headers",
                "db_table": "definition_of_headers",
            },
        ),
        migrations.CreateModel(
            name="role_matrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_id", models.TextField(blank=True, null=True)),
                ("role_name", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("owners", models.TextField(blank=True, null=True)),
                ("access_level", models.TextField(blank=True, null=True)),
                ("modules", models.TextField(blank=True, null=True)),
                ("menu", models.TextField(blank=True, null=True)),
                ("transaction_type", models.TextField(blank=True, null=True)),
                ("sod", models.TextField(blank=True, null=True)),
                ("responsibilities", models.TextField(blank=True, null=True)),
                ("account_expiration_date", models.TextField(blank=True, null=True)),
                ("permissions", models.TextField(blank=True, null=True)),
                ("frequency", models.TextField(blank=True, null=True)),
                ("approval", models.TextField(blank=True, null=True)),
                ("hr_terms", models.TextField(blank=True, null=True)),
                ("reporting_structure", models.TextField(blank=True, null=True)),
                ("audit_trail", models.TextField(blank=True, null=True)),
                ("time_based", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Role Matrix",
                "verbose_name_plural": "Role Matrices",
                "db_table": "role_matrix",
            },
        ),
    ]
