# Generated by Django 5.1.5 on 2025-02-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_review", "0002_definition_of_headers_role_matrix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition_of_headers",
            name="header",
            field=models.TextField(blank=True, null=True),
        ),
    ]
