# Generated by Django 5.1.5 on 2025-02-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_review", "0003_alter_definition_of_headers_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="role_matrix",
            name="application",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
