# Generated by Django 5.1.5 on 2025-03-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_review", "0004_role_matrix_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="line_manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pf_no", models.CharField(blank=True, max_length=50, null=True)),
                ("sam_name", models.CharField(blank=True, max_length=100, null=True)),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=200, null=True)),
                (
                    "employee_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("subsidiary", models.CharField(blank=True, max_length=200, null=True)),
                ("department", models.CharField(blank=True, max_length=200, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("branch", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "actual_end_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name": "line_manager",
                "verbose_name_plural": "line_manager",
                "db_table": "line_manager",
            },
        ),
    ]
